### ISSUE TITLE
Cannot find module error after updating to 1.2.5

### ISSUE THREAD

**Issue by spadgett** [neoclide/coc-eslint#47]
This worked fine in 1.2.4, but fails after I update to 1.2.5. I get the following error:

> [coc.nvim] Cannot find module 'eslint-plugin-console' Referenced from: /Users/sam/work/console/frontend/packages/.eslintrc.js

#43 is the only change I see in the release.

The project I'm working on is https://github.com/openshift/console, which uses yarn workspaces. eslint works fine outside of vim.

```
## versions

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.74-15f685206a
term: iTerm.app
platform: darwin
```

**Comment by chemzqm** [comment]
Looks like you don't have that module installed.

**Comment by spadgett** [comment]
@chemzqm It's part of the project here:

https://github.com/openshift/console/tree/master/frontend/packages/eslint-plugin-console

**Comment by chemzqm** [comment]
It can't resolve module from packages folder,  it have to be installed to node_modules.
